import os
import structlog
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

from src.orchestrator.state import OrchestratorState

logger = structlog.get_logger()

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

# ─────────────────────────────────────────────────────────────────────────────
# Critic Audit Prompt
# ─────────────────────────────────────────────────────────────────────────────
AUDIT_PROMPT = """
You are a Chief Tech Editor auditing a product consensus review draft generated by an AI assistant.

Product: {name}
Brand: {brand}
Rating: {rating}
Verdict: {verdict}
Specs: {specs}
Pros: {pros}
Cons: {cons}

Review Sections Content (HTML pages):
{sections_text}

Specific Editor Correction Requests to Verify:
{editor_comments}

Run a detailed audit of the review:
1. Did the draft fully address all correction requests? (Answer yes/no and why)
2. Is the content authoritative, thorough, and structured? Does it avoid shallow summaries?
3. Does the text remain objective (not sounding like a sponsored advertisement)?

Respond with EXACTLY one of these formats:
- "PASS" if the review satisfies all conditions.
- "FAIL: <detailed critique of what is missing, incorrect, or shallow, and instructions for how to rewrite it>" if it fails.

Response:
"""

async def run_critic_agent(state: OrchestratorState) -> OrchestratorState:
    """
    Critic Agent Node:
    Performs automated format validations and executes a cognitive audit using Gemini 1.5 Pro.
    If the review fails, sets status to 'rejected' to loop back to Scribe.
    Enforces a maximum of 3 rewrite attempts before auto-passing.
    """
    logger.info("Critic Agent: Auditing generated review...", product=state.get("name"))
    
    # ── 1. Automated Format Checks ───────────────────────────────────────────
    validation_errors = []
    
    if not state.get("name") or state["name"] == state.get("video_title"):
        validation_errors.append("Product name is missing or matches default video title.")
        
    if not state.get("review_sections") or len(state["review_sections"]) < 2:
        validation_errors.append("Review must contain at least 2 structured section pages.")
        
    if not state.get("specs") or len(state["specs"]) == 0:
        validation_errors.append("Specifications dictionary cannot be empty.")
        
    if not state.get("pros") or len(state["pros"]) == 0:
        validation_errors.append("Pros list cannot be empty.")
        
    if not state.get("cons") or len(state["cons"]) == 0:
        validation_errors.append("Cons list cannot be empty.")
        
    rating = state.get("rating", 0.0)
    if rating < 1.0 or rating > 5.0:
        validation_errors.append(f"Rating {rating} must be a value between 1.0 and 5.0.")

    if validation_errors:
        error_msg = "; ".join(validation_errors)
        logger.warn("Critic Agent: Failed automated validation checks", errors=error_msg)
        state["editor_comments"] = f"Automated audit failures: {error_msg}"
        state["status"] = "rejected"
        state["attempt_count"] = state.get("attempt_count", 0) + 1
        return state

    # ── 2. Max Retry Escape Gate ──────────────────────────────────────────────
    attempt_count = state.get("attempt_count") or 0
    if attempt_count >= 3:
        logger.info("Critic Agent: Max rewrite attempts reached (3). Forcing approval.", job_uuid=str(state["job_uuid"]))
        state["status"] = "enriching"
        return state

    # ── 3. Cognitive Quality Audit via LLM ──────────────────────────────────
    try:
        # Construct content string of sections for audit context
        sections_text = ""
        for sec in state["review_sections"]:
            sections_text += f"\n--- Page {sec.get('page_index')}: {sec.get('title')} ---\n{sec.get('content_html')}\n"

        editor_comments = state.get("editor_comments", "")
        if not editor_comments:
            editor_comments = "None. Verify general quality, flow, spelling, and structure."

        llm_pro = ChatGoogleGenerativeAI(
            model="gemini-1.5-flash-latest",
            google_api_key=GEMINI_API_KEY,
            temperature=0.0
        )
        prompt_tmpl = ChatPromptTemplate.from_template(AUDIT_PROMPT)
        chain = prompt_tmpl | llm_pro
        
        res = await chain.ainvoke({
            "name": state["name"],
            "brand": state["brand"],
            "rating": state["rating"],
            "verdict": state["verdict"],
            "specs": str(state["specs"]),
            "pros": str(state["pros"]),
            "cons": str(state["cons"]),
            "sections_text": sections_text,
            "editor_comments": editor_comments
        })
        
        audit_result = res.content.strip()
        
        if audit_result.startswith("PASS"):
            logger.info("Critic Agent: Quality audit PASSED.")
            state["status"] = "enriching"
        else:
            critique = audit_result.replace("FAIL:", "").strip()
            logger.warn("Critic Agent: Quality audit FAILED.", critique=critique)
            state["editor_comments"] = critique
            state["status"] = "rejected"
            state["attempt_count"] = attempt_count + 1

    except Exception as e:
        logger.error("Critic Agent: Exception occurred during audit, bypassing", error=str(e))
        # Default pass in case of audit exception to prevent pipeline lockups
        state["status"] = "enriching"

    return state
